name: Tests
on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: spring-boot:test-run
        run: |
          cd api
          ./mvnw --batch-mode --update-snapshots verify
